title: Archetect (sic)
author: Jimmie Fulton
theme: jekyll-theme-slate
description: > # Archetect is a powerful, language agnostic content generator capable of rendering files, projects, 
  and entire architectures. Like Maven Archetypes, but easier to author and publish archetypes, and like cookiecutter,
  but more powerful, and built for the enterprise.
