[book]
authors = ["Jimmie Fulton"]
language = "en"
multilingual = false
src = "src"
title = "Archetect Documentation"

[output.html]
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/archetect/archetect.github.io"
